from __future__ import annotations

import logging
from abc import abstractmethod
from copy import deepcopy
from dataclasses import dataclass

from typing_extensions import List, Iterator, Optional, Iterable

from krrood.entity_query_language.predicate import Predicate
from coraplex.datastructures.dataclasses import Context
from semantic_digital_twin.adapters.ros.visualization.viz_marker import (
    VizMarkerPublisher,
)
from semantic_digital_twin.collision_checking.collision_rules import (
    AvoidExternalCollisions,
    AllowSelfCollisions,
)
from semantic_digital_twin.robots.robot_parts import AbstractRobot
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World

logger = logging.getLogger("coraplex")


@dataclass
class Location(Iterable[Pose]):
    """
    Base for all locations that can be used to plan movements.
    """

    context: Optional[Context]
    """
    The context where the location can extract information about the robot and world from.
    """

    target_pose: Pose
    """
    The target pose for the location.
    """

    generator: PoseGeneratorBackend
    """
    Backend that generates pose candidates.
    """
    validators: List[PoseValidator]
    """
    Validators that are used to check if a generated pose is valid.
    """

    @property
    def world(self):
        return self.context.world

    @property
    def robot(self):
        return self.context.robot

    def ground(self) -> Pose:
        """
        :return: The first pose generated by this location designator
        """
        return next(iter(self))

    def __iter__(self) -> Iterator[Pose]:
        test_world = deepcopy(self.world)
        test_robot = test_world.get_semantic_annotations_by_type(type(self.robot))[0]
        for validator in self.validators:
            validator.world = test_world
            validator.robot = test_robot

        if self.context.debug:
            VizMarkerPublisher(
                _world=test_world, node=self.context.ros_node
            ).with_tf_publisher()

        for pose_candidate in self.generator:

            test_robot.root.parent_connection.origin = pose_candidate

            test_world.collision_manager.clear_temporary_rules()
            test_world.collision_manager.add_temporary_rule(
                AvoidExternalCollisions(robot=test_robot)
            )
            test_world.collision_manager.add_temporary_rule(
                AllowSelfCollisions(robot=test_robot)
            )
            test_world.collision_manager.update_collision_matrix()
            collisions = test_world.collision_manager.compute_collisions()

            if collisions.contacts:
                logger.debug(f"Candidate pose in collision, skipping")
                continue

            if all(
                validator(pose_candidate=pose_candidate)
                for validator in self.validators
            ):
                yield pose_candidate

    def merge(self, other: Location) -> Location:
        """
        Merge this location with another location, merging the generator backends and validators.

        :param other: The other location to merge with.
        :return: A new location that is the merge of this location and the other location.
        """
        return Location(
            self.context,
            self.target_pose,
            self.generator.merge(other.generator),
            self.validators + other.validators,
        )

    def __and__(self, other: Location) -> Location:
        return self.merge(other)


@dataclass
class PoseGeneratorBackend:
    """
    Generator backend base class for poses, generates pose candidates which are checked against a set of validators.
    """

    @abstractmethod
    def __iter__(self) -> Iterator[Pose]:
        pass

    def merge(self, other: PoseGeneratorBackend) -> PoseGeneratorBackend:
        """
        Merge this pose generator backend with another pose generator backend. The resulting pose generator backend
        generates pose candidates that are generated by both pose generator backends.

        :param other: The other pose generator backend to merge with.
        :return: A new pose generator backend that is the merge of this pose generator backend and the other pose generator backend.
        """
        pass

    def __and__(self, other: PoseGeneratorBackend) -> PoseGeneratorBackend:
        return self.merge(other)


@dataclass
class PoseValidator(Predicate):
    """
    Validates a pose candidate.
    """

    world: World
    """
    The world in which the pose candidate should be validated.
    """

    robot: AbstractRobot
    """
    The robot that should be used to validate the pose candidate.
    """

    @abstractmethod
    def __call__(self, *args, **kwargs) -> bool:
        pass
