name: CI reusable
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  workflow_call:
    inputs:
      lib:
        description: "Library folder name (relative to repo root)"
        required: true
        type: string
      repo_lowercase:
        description: "Lowercase repository name with tag"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.repo_lowercase }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: cognitive_robot_abstract_machine
          submodules: recursive

      - name: Install dependencies
        run: |
          cd cognitive_robot_abstract_machine
          source /opt/ros/cram-env/bin/activate
          sudo apt-get update
          sudo apt-get install -y xvfb libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0 libegl1
          uv sync --extra dev --active
          uv tree --depth 1
          python -c "import sys; print(sys.executable)"

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: /github/home/.cache/semantic_digital_twin
          key: ${{ runner.os }}-cache-${{ inputs.lib }}-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ inputs.lib }}-${{ github.ref_name }}
            ${{ runner.os }}-cache-${{ inputs.lib }}
            ${{ runner.os }}-cache-

      - name: Build ORM
        if: ${{inputs.lib == 'coraplex' || inputs.lib == 'semantic_digital_twin' || inputs.lib == 'experiments'}}
        run: |
          cd cognitive_robot_abstract_machine/${{ inputs.lib }}/scripts/
          source /opt/ros/cram-env/bin/activate
          source /opt/ros/overlay_ws/install/setup.bash
          python generate_orm.py

      - name: Run CPP tests
        if: ${{inputs.lib == 'random_events'}}
        run: |
          cd cognitive_robot_abstract_machine/${{ inputs.lib }}/src/random_events_lib
          sudo apt-get install -y g++ unzip zip
          BAZEL_VERSION=7.0.0
          curl -L -o bazel.sh \
            https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
          chmod +x bazel.sh
          ./bazel.sh --user
          export PATH="$HOME/bin:$PATH"
          
          bazel build //test:test_all
          bazel test //test:test_all

      - name: Run tests
        run: |
          source /opt/ros/cram-env/bin/activate
          source /opt/ros/overlay_ws/install/setup.bash
          echo "PYTHONPATH: $PYTHONPATH"
          if [[ "${{ inputs.lib }}" == "probabilistic_model" ]]; then
            export QT_QPA_PLATFORM=offscreen
          fi
          python -m pytest -sv -n auto cognitive_robot_abstract_machine/test/${{ inputs.lib }}_test

      - name: Save cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: /github/home/.cache/semantic_digital_twin
          key: ${{ runner.os }}-cache-${{ inputs.lib }}-${{ github.ref_name }}-${{ github.run_id }}
